addons: add monitoring overlay
omnivector-solutions/slurm-bundles pull request #19
Opened 2021-07-27 18:48 UTC by heitorPB

This overlay deploys a Prometheus2 instance and prometheus-node-exporter
to all nodes in the cluster.

2021-07-28 16:11 UTC, dusktreader requested changes

2021-07-28 16:11 UTC, dusktreader commented on slurm-addons/monitoring.yaml
> +  - - prometheus2:scrape
I think it would be a lot more readable to use the inline syntax for lists in these items:

```yaml
relations:
  - [prometheus2:scrape, node-exporter:prometheus]
  - [node-exporter:juju-info, slurmd:juju-info]
```

2021-07-28 21:19 UTC, heitorPB commented on slurm-addons/monitoring.yaml
> +  - - prometheus2:scrape
I liked that! But i think it would be better to leave that for another PR, just to have the same pattern across the repo.

Thoughts @jamesbeedy ?

2021-07-29 19:10 UTC, jamesbeedy commented
👍

2021-07-29 19:11 UTC, merged