Update README with better description for Charmhub
omnivector-solutions/slurm-bundles pull request #25
Opened 2022-06-28 20:52 UTC by heitorPB

Solves INFRA-655

2022-06-28 21:16 UTC, dusktreader requested changes
Very nice update. Added a few comments for you.

2022-06-28 21:16 UTC, dusktreader commented on README.md
> +A suite of codified operations to assemble, install, deploy, and operate
This is a sentence fragment. Maybe:
```suggestion
This suite provides a set of codified operations to assemble, install, deploy, and operate
```

2022-06-28 21:16 UTC, dusktreader commented on README.md
> +- 1 `percona-cluster` node: the MySQL database
```suggestion
This command will deploy and configure a Slurm cluster with one of each of the following nodes:
- `slurmctld`: the central management node
- `slurmdbd`: the database accounting node
- `slurmd`: the compute node
- `slurmrestd`: the REST API interface to Slurm
- `percona-cluster`: the MySQL database
```

2022-06-29 17:15 UTC, heitorPB commented on README.md
> +- 1 `percona-cluster` node: the MySQL database
Oh, way better, thanks!

2022-07-05 20:29 UTC, dusktreader approved these changes

2022-07-07 11:57 UTC, merged