Dev kelly
omnivector-solutions/slurm-bundles pull request #28
Opened 2022-08-16 17:02 UTC by omnivector-kelly

Add support for Juju Resources for NHC.

2022-08-16 18:25 UTC, heitorPB requested changes
Nice work! I have left some minor suggestions for your PR.

2022-08-16 18:25 UTC, heitorPB commented on Makefile
> +${NHC}:
```suggestion
${NHC}: ## Download NHC resource
```

2022-08-16 18:25 UTC, heitorPB commented on Makefile
> +lxd-focal: ${ETCD} ${NHC}## Deploy slurm-core in a local LXD Ubuntu Focal cluster
```suggestion
lxd-focal: ${ETCD} ${NHC} ## Deploy slurm-core in a local LXD Ubuntu Focal cluster
```

2022-08-16 18:25 UTC, heitorPB commented on Makefile
> +lxd-centos: ${ETCD} ${NHC}## Deploy slurm-core in a local LXD CentOS7 cluster
```suggestion
lxd-centos: ${ETCD} ${NHC} ## Deploy slurm-core in a local LXD CentOS7 cluster
```

2022-08-16 18:25 UTC, heitorPB commented on Makefile
> +aws-focal: ${ETCD} ${NHC}## Deploy slurm-core in a AWS Ubuntu Focal cluster
```suggestion
aws-focal: ${ETCD} ${NHC} ## Deploy slurm-core in a AWS Ubuntu Focal cluster
```

2022-08-16 18:25 UTC, heitorPB commented on Makefile
> +aws-centos: ${ETCD} ${NHC}## Deploy slurm-core in a AWS CentOS7 cluster
```suggestion
aws-centos: ${ETCD} ${NHC} ## Deploy slurm-core in a AWS CentOS7 cluster
```

2022-08-16 18:25 UTC, heitorPB commented on slurm-core/bundle.yaml
> +      nhc: ./../lbnl-nhc-1.4.3.tar.gz
Could you move this to the `slurm-core/charms/local-development.yaml` file? We only need to pass a path to a local file in our dev setup, when not a dev setup we can get the resource from Charmhub.

2022-08-17 15:43 UTC, omnivector-kelly commented on slurm-core/bundle.yaml
> +      nhc: ./../lbnl-nhc-1.4.3.tar.gz
This has been moved. https://github.com/omnivector-solutions/slurm-bundles/commit/2e67d6e0bd49038f15fe08470441506d253c5daf

2022-08-29 19:47 UTC, heitorPB commented
@omnivector-kelly could you rebase the code to solve the conflicts please?

2022-08-30 16:59 UTC, heitorPB approved these changes
Nice work!

2022-08-30 17:49 UTC, merged