Remove snaps
omnivector-solutions/slurm-bundles pull request #4
Opened 2021-04-06 14:27 UTC by heitorPB

2021-04-08 14:10 UTC, zsinx6 commented on slurm-core/bundle.yaml
> +#   num_units: 1
Why keep things commented?

2021-04-08 14:19 UTC, heitorPB commented on slurm-core/bundle.yaml
> +#   num_units: 1
this will be un-commented later. We currently have a problem with slurmrestd on centos.

2021-04-08 14:21 UTC, zsinx6 commented on slurm-core/bundle.yaml
> +#   num_units: 1
Maybe add that to the line above the comments then

2021-04-09 19:38 UTC, jamesbeedy requested changes
possibly we make a new top level namespace for the `bundle.yaml` file in `slurm-core/` and combine the `series/*.yaml ` with the `bundle.yaml`?

`slurm-core/centos7/bundle.yaml`
`slurm-core/focal/bundle.yaml`

This way we can keep the slurmrestd charm and relations included in the focal bundle.

Thoughts?

2021-04-09 19:47 UTC, heitorPB commented
What about moving the `slurmrestd` application to the `focal.yaml`? This way we have `slurmrestd` only when selecting the `focal.yaml` overlay.

2021-04-09 19:50 UTC, jamesbeedy commented
> What about moving the `slurmrestd` application to the `focal.yaml`? This way we have `slurmrestd` only when selecting the `focal.yaml` overlay.

I like this. 👍

2021-04-09 21:23 UTC, jamesbeedy commented
@zsinx6 @heitorPB thoughts on this hierarchy?

2021-04-09 22:10 UTC, jamesbeedy commented
I'm going to merge and release this. We can talk about changing the folder structure later but I think this makes good sense for now.

2021-04-09 22:11 UTC, merged

2021-04-10 00:21 UTC, heitorPB commented on slurm-core/focal/options/edge-snap.yaml
> +      snapstore-channel: "--edge"
The pull request named "Remove snaps" allows snaps :stuck_out_tongue_winking_eye: 

Let's discuss discus this on Monday.

2021-04-10 00:42 UTC, jamesbeedy commented on slurm-core/focal/options/edge-snap.yaml
> +      snapstore-channel: "--edge"
🤦